import {
  BedDouble,
  Car,
  Compass,
  Plane,
  Ship,
  TrainFront,
  Utensils,
} from "lucide-react";

export const destinations = [
  {
    id: "kannauj",
    number: "01",
    badge: "Signature",
    badgeColor: "orange",
    inclusions: ["Hotel", "Meals", "Cabs", "Guide"],
    // Per-person price in ₹. Set both to show the price, strike-through and % OFF.
    price: null,
    originalPrice: null,
    title: "Kannauj Fragrance Trail",
    region: "Uttar Pradesh",
    route: "Agra → Kannauj",
    duration: "1 Day / 2 Nights",
    meals: "As per programme",
    image: "/traditional attar.jpg",
    summary:
      "Journey from Agra into India's perfume capital — flower fields, traditional attar distillation, the fragrance market and a perfumer family.",
    highlights: [
      "Rose & jasmine flower fields",
      "Traditional deg-bhapka attar unit",
      "Kannauj perfume market",
      "Hi-tea with a perfumer family",
      "Incense-stick factory",
      "Gauri Shankar Temple",
    ],
    days: [
      {
        day: "Day 01",
        title: "Arrival, Perfumer Connection & Heritage",
        text: "Depart Agra / Lucknow after lunch, check in, hi-tea with a perfumer family and an evening visit to Gauri Shankar Temple.",
      },
      {
        day: "Day 02",
        title: "From Flower Fields to Attar",
        text: "Early morning rose / jasmine field visit, traditional attar experience, perfume market and incense-stick factory.",
      },
      {
        day: "Day 03",
        title: "Breakfast & Departure",
        text: "Breakfast, hotel check-out and continue towards Agra or Lucknow.",
      },
    ],
    link: "/#journey",
  },
  {
    id: "north-india",
    number: "02",
    badge: "Classic Circuit",
    badgeColor: "red",
    inclusions: ["Hotel", "Meals", "Cabs", "Train", "Flights"],
    // Per-person price in ₹. Set both to show the price, strike-through and % OFF.
    price: null,
    originalPrice: null,
    title: "Classical North India",
    region: "Delhi · Rajasthan · Agra · Varanasi",
    route: "Delhi → Rajasthan → Agra → Khajuraho → Varanasi",
    duration: "14 Days",
    meals: "Half board basis",
    image: "/destination/covers/north-india.jpg",
    summary:
      "The great northern circuit — Mughal Delhi, the painted havelis and desert forts of Rajasthan, the Taj Mahal, the temples of Khajuraho and the ghats of Varanasi.",
    highlights: [
      "Old & New Delhi, Qutub Minar",
      "Shekhawati havelis of Mandawa",
      "Mehrangarh Fort, Jodhpur",
      "Amber Fort, Jaipur",
      "Taj Mahal & Fatehpur Sikri",
      "Khajuraho temples",
      "Ganga Aarti, Varanasi",
    ],
    days: [
      { day: "Day 01", title: "Arrival Delhi", text: "Meet & greet at the airport and transfer to hotel." },
      { day: "Day 02", title: "In Delhi", text: "Old Delhi — Red Fort, Jama Masjid, Chandni Chowk — and New Delhi, ending at Qutub Minar." },
      { day: "Day 03", title: "Drive Delhi – Mandawa", text: "Drive (270 km) to the painted-haveli town of Mandawa in Shekhawati." },
      { day: "Day 04", title: "Drive Mandawa – Bikaner", text: "Drive (190 km) to the desert city of Bikaner, founded by Rao Bikaji in 1488." },
      { day: "Day 05", title: "Drive Bikaner – Jodhpur", text: "Continue to Jodhpur; walking tour of the local bazaars and Clock Tower area." },
      { day: "Day 06", title: "Drive Jodhpur – Jaipur", text: "Drive to Jaipur, the Pink City." },
      { day: "Day 07", title: "In Jaipur", text: "Morning at Amber Fort; afternoon city tour of Jaipur." },
      { day: "Day 08", title: "Drive Jaipur – Agra", text: "En route visit Fatehpur Sikri, then continue to Agra and the Taj Mahal." },
      { day: "Day 09", title: "Train Agra – Jhansi – Khajuraho", text: "Shatabdi Express to Jhansi, then drive (4–5 hrs) to Khajuraho." },
      { day: "Day 10", title: "In Khajuraho", text: "Eastern & Western Group of Temples by bullock cart, including Kandariya Mahadeo." },
      { day: "Day 11", title: "Drive Khajuraho – Allahabad", text: "Drive (300 km) to Allahabad (Prayagraj), the city of the Sangam." },
      { day: "Day 12", title: "Drive Allahabad – Varanasi", text: "Visit Anand Bhawan, drive to Varanasi; evening rickshaw tour of the old town." },
      { day: "Day 13", title: "Fly Varanasi – Delhi", text: "Morning city tour of Varanasi ending at Bharat Mata Temple, then fly to Delhi." },
      { day: "Day 14", title: "Fly out from Delhi", text: "Transfer to the airport for your onward flight." },
    ],
    pdf: "/destination/1-NorthIndiaClassicalTrip.pdf",
  },
  {
    id: "rajasthan",
    number: "03",
    badge: "Royal Heritage",
    badgeColor: "purple",
    inclusions: ["Hotel", "Meals", "Cabs", "Train"],
    // Per-person price in ₹. Set both to show the price, strike-through and % OFF.
    price: null,
    originalPrice: null,
    title: "Classical Rajasthan",
    region: "Rajasthan · Agra",
    route: "Delhi → Jaisalmer → Udaipur → Jaipur → Agra",
    duration: "16 Days",
    meals: "Half board basis",
    image: "/destination/covers/rajasthan.jpg",
    summary:
      "A royal loop through the land of kings — golden Jaisalmer, blue Jodhpur, the lakes of Udaipur, holy Pushkar, pink Jaipur, tigers of Ranthambhore and the Taj Mahal.",
    highlights: [
      "Jaisalmer Fort & Gadisar Lake",
      "Mehrangarh Fort, Jodhpur",
      "Private yoga session in Udaipur",
      "Pushkar Lake & Brahma Temple",
      "Amber Fort, Jaipur",
      "Ranthambhore National Park",
      "Taj Mahal, Agra",
    ],
    days: [
      { day: "Day 01", title: "Arrival Delhi", text: "Meet & greet at the airport and transfer to hotel." },
      { day: "Day 02", title: "In Delhi", text: "Old Delhi and New Delhi sightseeing, ending at Qutub Minar." },
      { day: "Day 03", title: "Drive Delhi – Mandawa", text: "Drive to Mandawa and its painted Shekhawati havelis." },
      { day: "Day 04", title: "Drive Mandawa – Bikaner", text: "Drive (190 km) to the desert city of Bikaner." },
      { day: "Day 05", title: "Drive Bikaner – Jaisalmer", text: "Drive to Jaisalmer and its towering yellow-sandstone fort." },
      { day: "Day 06", title: "In Jaisalmer", text: "Morning tour of Gadisar Lake and Jaisalmer Fort." },
      { day: "Day 07", title: "Drive to Jodhpur", text: "Drive to Jodhpur; walking tour of bazaars and the Clock Tower area." },
      { day: "Day 08", title: "Drive to Udaipur", text: "Drive to Udaipur, the city of lakes." },
      { day: "Day 09", title: "In Udaipur", text: "Early morning private yoga session, followed by Udaipur sightseeing." },
      { day: "Day 10", title: "Drive Udaipur – Pushkar", text: "Drive to Pushkar; afternoon walking tour of the town and Brahma Temple." },
      { day: "Day 11", title: "Drive Pushkar – Jaipur", text: "Drive (3 hrs) to Jaipur, the Pink City." },
      { day: "Day 12", title: "In Jaipur", text: "Morning at Amber Fort; afternoon city tour of Jaipur." },
      { day: "Day 13", title: "Drive Jaipur – Ranthambhore", text: "Drive (180 km) to Ranthambhore National Park, former hunting preserve of the Maharajas." },
      { day: "Day 14", title: "Train to Bharatpur & drive to Agra", text: "Morning train to Bharatpur, then continue to Agra." },
      { day: "Day 15", title: "Agra – Delhi", text: "Morning visit to the Taj Mahal, then drive (200 km) to Delhi." },
      { day: "Day 16", title: "Fly out from Delhi", text: "Transfer to the airport for your onward flight." },
    ],
    pdf: "/destination/2-RajasthanClassicalTrip.pdf",
  },
  {
    id: "tamilnadu-kerala",
    number: "04",
    badge: "Temples & Backwaters",
    badgeColor: "green",
    inclusions: ["Hotel", "Meals", "Cabs", "Houseboat"],
    // Per-person price in ₹. Set both to show the price, strike-through and % OFF.
    price: null,
    originalPrice: null,
    title: "Tamil Nadu & Kerala",
    region: "Tamil Nadu · Kerala",
    route: "Chennai → Madurai → Munnar → Alleppey → Cochin",
    duration: "15 Days",
    meals: "As per itinerary",
    image: "/destination/covers/tamilnadu-kerala.jpg",
    summary:
      "Dravidian temple towns and French Pondicherry, Chettinad mansions, tea-covered Munnar, Periyar's jungles and a houseboat through Kerala's backwaters.",
    highlights: [
      "Shore Temple, Mahabalipuram",
      "Auroville & Pondicherry",
      "Chidambaram & Srirangam temples",
      "Chettinad mansions",
      "Meenakshi Temple, Madurai",
      "Munnar tea hills & Periyar",
      "Backwater houseboat, Alleppey",
    ],
    days: [
      { day: "Day 01", title: "Arrive Chennai & drive to Mahabalipuram", text: "Airport pick-up and orientation tour of Chennai en route to Mahabalipuram." },
      { day: "Day 02", title: "In Mahabalipuram", text: "Morning tour of the magnificent rock temples and carvings." },
      { day: "Day 03", title: "Drive Mahabalipuram – Pondicherry", text: "En route visit Auroville, the experimental international township." },
      { day: "Day 04", title: "In Pondicherry", text: "Visit Sri Aurobindo Ashram and Auroville, the City of Dawn." },
      { day: "Day 05", title: "Drive to Tanjore", text: "En route visit the Thillai Nataraja Temple at Chidambaram." },
      { day: "Day 06", title: "Drive to Chettinad via Trichy", text: "Visit Srirangam Temple at Trichy, then continue to Chettinad." },
      { day: "Day 07", title: "Drive to Madurai", text: "Chettinad Palace and mansions, then drive to Madurai; evening temple ceremony." },
      { day: "Day 08", title: "In Madurai", text: "Meenakshi Temple and Thirumalai Nayak Palace city tour." },
      { day: "Day 09", title: "Drive Madurai – Munnar", text: "Drive to Munnar, the hill station at the meeting of three mountain streams." },
      { day: "Day 10", title: "Drive Munnar – Periyar", text: "Afternoon private boat ride on Lake Periyar to spot wildlife." },
      { day: "Day 11", title: "In Periyar", text: "Nature walk through the jungle with an English-speaking naturalist." },
      { day: "Day 12", title: "Drive Periyar – Kumarakom", text: "Afternoon responsible-tourism village experience (approx. 3 hrs)." },
      { day: "Day 13", title: "Kumarakom – Alleppey", text: "Board a traditional houseboat on the backwaters." },
      { day: "Day 14", title: "Alleppey – Cochin", text: "Disembark and drive to Cochin for a tour of Fort Cochin." },
      { day: "Day 15", title: "Fly out from Cochin", text: "Transfer to the international airport." },
    ],
    pdf: "/destination/3-Tamilnadu%26KeralaTour.pdf",
  },
  {
    id: "south-india",
    number: "05",
    badge: "Grand South",
    badgeColor: "orange",
    inclusions: ["Hotel", "Meals", "Cabs", "Houseboat"],
    // Per-person price in ₹. Set both to show the price, strike-through and % OFF.
    price: null,
    originalPrice: null,
    title: "Classical South India",
    region: "Karnataka · Kerala · Tamil Nadu",
    route: "Bangalore → Mysore → Ooty → Cochin → Chennai",
    duration: "16 Days",
    meals: "Half board basis",
    image: "/destination/covers/south-india.jpg",
    summary:
      "Three southern states in one journey — Hoysala temples and royal Mysore, the Nilgiri toy train, Kerala's backwaters and spice gardens, and Tamil Nadu's great temple towns.",
    highlights: [
      "Shravanabelagola & Somnathpur",
      "Mysore & Srirangapatna",
      "Nilgiri toy train, Ooty",
      "Fort Cochin & Chinese fishing nets",
      "Alleppey houseboat",
      "Thekkady spice plantation",
      "Madurai, Tanjore & Mahabalipuram",
    ],
    days: [
      { day: "Day 01", title: "Arrive Bangalore", text: "Evening arrival and transfer to hotel." },
      { day: "Day 02", title: "Drive to Hassan", text: "Orientation tour of Bangalore — Vidhan Sabha, Lal Bagh, Bull Temple — en route." },
      { day: "Day 03", title: "Hassan – Mysore", text: "Visit Shravanabelagola en route; afternoon city tour of Mysore." },
      { day: "Day 04", title: "In Mysore", text: "Hoysala temple at Somnathpur and Srirangapatna in the afternoon." },
      { day: "Day 05", title: "Mysore – Ooty", text: "Drive to Ooty; afternoon toy-train ride to Coonoor." },
      { day: "Day 06", title: "Ooty – Cochin", text: "Drive down to Cochin." },
      { day: "Day 07", title: "In Cochin", text: "Fort Cochin, the oldest European settlement in India, and the Chinese fishing nets." },
      { day: "Day 08", title: "Cochin – Alleppey", text: "Embark on a traditional houseboat on the backwaters." },
      { day: "Day 09", title: "Alleppey – Periyar", text: "Drive to Periyar and visit a Thekkady spice plantation." },
      { day: "Day 10", title: "Periyar – Madurai", text: "Drive to Madurai, visiting rope making and a small school en route." },
      { day: "Day 11", title: "In Madurai", text: "Meenakshi Temple and Thirumalai Nayak Palace." },
      { day: "Day 12", title: "Madurai – Trichy – Tanjore", text: "Visit the vast Srirangam Temple at Trichy, then on to Tanjore." },
      { day: "Day 13", title: "Tanjore – Pondicherry", text: "En route visit the Nataraja Temple at Chidambaram." },
      { day: "Day 14", title: "Pondicherry – Chennai", text: "En route visit the ancient coastal port of Mahabalipuram." },
      { day: "Day 15", title: "In Chennai", text: "City tour of Chennai." },
      { day: "Day 16", title: "Fly out from Chennai", text: "Morning flight home." },
    ],
    pdf: "/destination/4-SouthIndiaClassicltrip.pdf",
  },
  {
    id: "srinagar-ladakh",
    number: "06",
    badge: "Himalayan",
    badgeColor: "purple",
    inclusions: ["Hotel", "Meals", "Cabs", "Flights"],
    // Per-person price in ₹. Set both to show the price, strike-through and % OFF.
    price: null,
    originalPrice: null,
    title: "Srinagar & Ladakh",
    region: "Kashmir · Ladakh",
    route: "Delhi → Srinagar → Kargil → Leh → Nubra → Pangong",
    duration: "18 Days",
    meals: "As per itinerary",
    image: "/destination/covers/srinagar-ladakh.jpg",
    summary:
      "Houseboats and Mughal gardens in Srinagar, then the high road over the Himalaya into Ladakh — monasteries, Khardung La, the Nubra dunes and the blue waters of Pangong.",
    highlights: [
      "Dal Lake houseboat stay",
      "Mughal gardens & Gulmarg",
      "Thiksey Monastery morning prayer",
      "Leh old-town heritage walk",
      "Khardung La & Nubra Valley",
      "Pangong Lake camp",
      "Alchi & Lamayuru monasteries",
    ],
    days: [
      { day: "Day 01", title: "Arrival Delhi", text: "Meet & greet at the airport and transfer to hotel." },
      { day: "Day 02", title: "In Delhi", text: "Full-day city tour of Delhi." },
      { day: "Day 03", title: "Fly Delhi – Srinagar", text: "Morning flight to Srinagar and transfer to a houseboat on the lake." },
      { day: "Day 04", title: "In Srinagar", text: "Mughal gardens Nishat & Shalimar Bagh; afternoon old-city tour and Jamia Masjid." },
      { day: "Day 05", title: "In Srinagar", text: "Full-day excursion to Gulmarg, the Meadow of Flowers (2,730 m)." },
      { day: "Day 06", title: "Drive Srinagar – Kargil", text: "Scenic mountain drive to Kargil." },
      { day: "Day 07", title: "Drive Kargil – Leh", text: "Drive (5 hrs) to Leh; evening at leisure to acclimatise." },
      { day: "Day 08", title: "In Leh", text: "Morning prayer ceremony at Thiksey Monastery and an audience with a Geshe." },
      { day: "Day 09", title: "In Leh", text: "Guided heritage walk of the old town and the Central Asian Museum." },
      { day: "Day 10", title: "Drive Leh – Nubra", text: "Cross Khardung La (18,380 ft), one of the highest motorable roads in the world." },
      { day: "Day 11", title: "In Nubra", text: "Morning prayer at Diskit Monastery." },
      { day: "Day 12", title: "Drive Nubra – Pangong", text: "Drive to Pangong Lake; overnight in camps." },
      { day: "Day 13", title: "Drive Pangong – Leh", text: "Explore the lakeshore, then drive back to Leh." },
      { day: "Day 14", title: "Drive Leh – Uleytokpo", text: "Visit Likir and Alchi en route." },
      { day: "Day 15", title: "In Uleytokpo", text: "Excursion to Lamayuru, the oldest monastery in Ladakh." },
      { day: "Day 16", title: "Drive Uleytokpo – Leh", text: "Return drive to Leh." },
      { day: "Day 17", title: "Fly Leh – Delhi", text: "Flight to Delhi; room until departure." },
      { day: "Day 18", title: "Fly out from Delhi", text: "Board your onward international flight." },
    ],
    pdf: "/destination/5-Srinagar-Ladakh-Trip.pdf",
  },
];

export const getDestination = (slug) =>
  destinations.find((item) => item.id === slug);

export const badgeStyles = {
  orange: "bg-[#ef8b19]",
  red: "bg-[#e5484d]",
  purple: "bg-[#7c3aed]",
  green: "bg-[#16a34a]",
};

export const inclusionIcons = {
  Hotel: { icon: BedDouble, color: "text-[#2563eb]" },
  Meals: { icon: Utensils, color: "text-[#ef8b19]" },
  Cabs: { icon: Car, color: "text-[#16a34a]" },
  Guide: { icon: Compass, color: "text-[#082f4f]" },
  Flights: { icon: Plane, color: "text-[#0ea5e9]" },
  Train: { icon: TrainFront, color: "text-[#7c3aed]" },
  Houseboat: { icon: Ship, color: "text-[#0d9488]" },
};

export const formatINR = (n) => `₹${n.toLocaleString("en-IN")}`;
